config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#index'

  resources :electric_cars, only: [:show]
  resources :orders, only: [:new, :create]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :electric_cars, only: [:index]
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/electric_car.rb
class ElectricCar < ApplicationRecord
  has_many :orders

  validates :brand, :model, :colors, :specification,
            :description, :price, presence: true

  validates :brand, :model, length: { maximum: 50 }

  def price_in_dollars
    (price.to_d / 100).to_f
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :electric_car

  validates :first_name, :last_name, :email, :phone_number,
            :electric_car_id, presence: true
end

app/controllers/api/v1/electric_cars_controller.rb
class Api::V1::ElectricCarsController < ApplicationController
  def index
    @electric_cars = ElectricCar.all
    render :index, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/electric_cars_controller.rb
class ElectricCarsController < ApplicationController
  def show
    @electric_car = ElectricCar.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      flash[:success] = 'Order has been successfully created. Our manager will contact you soon.'
      redirect_to electric_car_path(@order.electric_car_id)
    else
      flash[:alert] = 'Some of the order details are incorrect. '\
                      'Please update the form with correct details'
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:electric_car_id, :first_name, :last_name, :email, :phone_number)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/electric_cars_helper.rb
module ElectricCarsHelper
  def electric_car_title(car)
    "#{car.brand} - #{car.model}"
  end
end

app/views/electric_cars/show.html.erb
<div class="row car-item">
  <div class="col-xs-12 col-md-6">
    <img class="car-item--img" src="http://placehold.it/700x400" alt="Test">
  </div>

  <div class="col-xs-12 col-md-6">
    <div class="car-item--title">
      <h4><%= "#{@electric_car.brand} - #{@electric_car.model}" %></h4>
      <h4><%= number_to_currency(@electric_car.price_in_dollars) %></h4>
    </div>

    <p><b>Brand: </b><%= @electric_car.brand %></p>
    <p><b>Model: </b><%= @electric_car.model %></p>
    <p><b>Available Colors:</b> <%= @electric_car.colors %></p>
    <p><b>Description: </b><%= @electric_car.description %></p>

    <div class="car-item--action">
      <%= link_to 'Buy this Car', new_order_path(electric_car_id: @electric_car.id), class: 'btn btn-success' %>
    </div>
  </div>

  <div class="col-xs-12">
    <br />
    <h3>Specification</h3>
    <p><%= @electric_car.specification %></p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer main-container">
  <div class="row">
    <div class="footer--block-item col-xs-6">
      <h3>About Store</h3>
      <p>
        Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit.
      </p>
      <p>Eos cumque dicta adipisci architecto culpa amet.</p>
    </div>

    <div class="footer--block-item col-xs-6">
      <h3>Information</h3>

      <ul class="footer--link-list">
        <li>
          <%= link_to 'Contact', '#' %>
        </li>

        <li>
          <%= link_to 'About Us', '#' %>
        </li>

        <li>
          <%= link_to 'Blog', '#' %>
        </li>
      </ul>
    </div>
  </div>

  <p class="footer--copyright">Copyright © Ordinary Mortal 2018 | All rights are not reserved</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECarsShop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body data-controller="<%= controller_name %>" data-action="<%= action_name %>">
    <header class="header">
      <nav class="header--nav main-container" role="navigation">
        <div class="header--logo">
          <%= link_to 'E-Cars Shop', root_path %>
        </div>

        <div class="header--nav-menu">
          <%= link_to 'Home', root_path, class: 'header--nav-menu-link' %>
          <%= link_to 'About', '#', class: 'header--nav-menu-link' %>
          <%= link_to 'Contact', '#', class: 'header--nav-menu-link' %>
          <%= link_to 'Blog', '#', class: 'header--nav-menu-link' %>
        </div>
      </nav>
    </header>

    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash flash--#{key}" %>
    <% end %>

    <%= content_for :content_header %>

    <div class="main-container">
      <%= yield %>
    </div>

    <hr class="footer-separator"/>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/orders/new.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
    <h3>Please fill in the form to complete the order</h3>

    <%= form_for @order, html: { class: 'form' } do |f| %>
      <%= f.hidden_field :electric_car_id, value: params[:electric_car_id] %>

      <div class="form--group">
        <%= f.label :first_name do %>
          <span class="form--required-sign">*</span>First Name:
        <% end %>

        <%= f.text_field :first_name, placeholder: 'Enter your first name', required: true %>
      </div>

      <div class="form--group">
        <%= f.label :last_name do %>
          <span class="form--required-sign">*</span>Last Name:
        <% end %>

        <%= f.text_field :last_name, placeholder: 'Enter your last name', required: true %>
      </div>

      <div class="form--group">
        <%= f.label :email do %>
          <span class="form--required-sign">*</span>Email:
        <% end %>

        <%= f.email_field :email, placeholder: 'Enter your email', required: true %>
      </div>

      <div class="form--group">
        <%= f.label :phone_number do %>
          <span class="form--required-sign">*</span>Phone Number:
        <% end %>

        <%= f.phone_field :phone_number, placeholder: 'Enter your phone number', pattern: "[0-9]{3}-[0-9]{3}-[0-9]{4}", required: true %>
        <span class="form--hint"><b>*</b> Format: 063-123-7890</span>
      </div>

      <div class="form--group">
        <%= f.label :comment %>
        <%= f.text_area :comment, placeholder: 'Please feel free to add any additional information...' %>
      </div>

      <div class="form--group">
        <%= f.submit 'Create Order', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/index.html.erb
<%= content_for :content_header do %>
  <div class="hero-image">
    <%= image_tag 'electric_car.svg', class: 'hero-image--item' %>
  </div>
<% end %>

<div id="react--car-list"></div>
<%= javascript_pack_tag 'electric_cars' %>